### ISSUE TITLE
[Bug]: Generation doesnt use Gradient.lerp() for gradients

### ISSUE THREAD

**Issue by MsYoda** [Iteo/theme_tailor#104]
### Desctibe the bug

I was trying to use package for Theme generation and have `Gradient` field in class. 
You can see its code
```dart
@tailorMixinComponent
class DeviceInfoIndicatorStyle extends ThemeExtension<DeviceInfoIndicatorStyle>
    with _$DeviceInfoIndicatorStyleTailorMixin {
  const DeviceInfoIndicatorStyle({
    required this.filledBarColor,
    required this.unfiledBarColor,
    required this.ringGradient,
    required this.barLabelStyle,
    required this.valueStyle,
    required this.unitStyle,
  });

  final Color filledBarColor;
  final Color unfiledBarColor;
  final Gradient ringGradient;
  final TextStyle barLabelStyle;
  final TextStyle valueStyle;
  final TextStyle unitStyle;
}
```
Package generates this `lerp()` method
```dart
  @override
  DeviceInfoIndicatorStyle lerp(
      covariant ThemeExtension<DeviceInfoIndicatorStyle>? other, double t) {
    if (other is! DeviceInfoIndicatorStyle)
      return this as DeviceInfoIndicatorStyle;
    return DeviceInfoIndicatorStyle(
      filledBarColor: Color.lerp(filledBarColor, other.filledBarColor, t)!,
      unfiledBarColor: Color.lerp(unfiledBarColor, other.unfiledBarColor, t)!,
      ringGradient: t < 0.5 ? ringGradient : other.ringGradient,
      barLabelStyle: TextStyle.lerp(barLabelStyle, other.barLabelStyle, t)!,
      valueStyle: TextStyle.lerp(valueStyle, other.valueStyle, t)!,
      unitStyle: TextStyle.lerp(unitStyle, other.unitStyle, t)!,
    );
  }
```
Or did I misunderstand and the Gradient field requires custom encoder ?

### Reproduction steps

Use `dart run build_runner build` for class in description.

### Expected behaviour

Use `Gradient.lerp()` method in generated `lerp` function

### Dart version

3.4.1

### Package version

3.0.1

### What platform are you seeing the problem on?

iOS, Android, Web, Windows, macOS, Linux

### Relevant log output

```shell
dart run build_runner build
[INFO] Generating build script completed, took 345ms
[INFO] Reading cached asset graph completed, took 301ms
[INFO] Checking for updates since last build completed, took 924ms
[INFO] Running build completed, took 13.3s
[INFO] Caching finalized dependency graph completed, took 190ms
[INFO] Succeeded after 13.5s with 28 outputs (53 actions)
```

**Comment by Rongix** [comment]
Hi,

We do have support for some commonly used types, as mentioned in our [documentation](https://github.com/Iteo/theme_tailor/tree/main/packages/theme_tailor_toolbox/lib/src/theme_tailor_encoder).

>ThemeTailor will attempt to provide a lerp method for types such as:
>Color
>Color?
>TextStyle
>TextStyle?

As you mentioned, you would need to provide the encoder for additional types. I looked into the `Gradient` from `dart:ui`. Since it does not expose any public fields, you won't be able to write an encoder for it directly.

However, there are several approaches you can take to resolve your issue:

a) In the DeviceInfoIndicatorStyle, add all the required colors/properties that compose the gradient.
b) Create an additional ThemeExtension class that provides a method to create a gradient and allows for lerping its properties. This class should probably take a list of an unknown size, and you will be able to write an encoder for it.


Additionally, you can check out this unlisted package that provides support for some additional types like MaterialColor: [Theme Tailor Toolbox](https://github.com/Iteo/theme_tailor/tree/main/packages/theme_tailor_toolbox/lib/src/theme_tailor_encoder).

**Comment by MsYoda** [comment]
Okay, thank you
